<?php

namespace AMAPBundle\Repository;

/**
 * categorieProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
