<?php

namespace AMAPBundle\Repository;

/**
 * entrepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entrepotRepository extends \Doctrine\ORM\EntityRepository
{
}
