<?php

namespace AMAPBundle\Repository;

/**
 * PaiementCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
