<?php

namespace AMAPBundle\Repository;

/**
 * TypePanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePanierRepository extends \Doctrine\ORM\EntityRepository
{
}
