amap_entrepot:
    resource: "@AMAPBundle/Controller/EntrepotController.php"
    type:     annotation

amap_stock:
    resource: "@AMAPBundle/Controller/StockController.php"
    type:     annotation

amap_type_panier:
    resource: "@AMAPBundle/Controller/TypePanierController.php"
    type:     annotation

amap_panier:
    resource: "@AMAPBundle/Controller/PanierController.php"
    type:     annotation

amap_produit:
    resource: "@AMAPBundle/Controller/ProduitController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

amap_gestionProduits:
    resource: "@AMAPBundle/Controller/GestionProduitsController.php"
    type:     annotation
amap_identification:
    resource: "@AMAPBundle/Controller/IdentificationController.php"
    type:     annotation

amap_home:
    resource: "@AMAPBundle/Controller/HomeController.php"
    type:     annotation
