<?php

namespace AdminBundle\Repository;

/**
 * ContratClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratClientRepository extends \Doctrine\ORM\EntityRepository
{
}
