<?php

namespace AdminBundle\Repository;

/**
 * EtatCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
